### ISSUE TITLE
Test FEATURE-1

### ISSUE THREAD

**Issue by Xaptured** [Xaptured/esports-arena_dashboard#14]
Test FEATURE-1

## Subtasks

- [x] Check all the components rendered properely or not [including styling]
- [x] Check sign up process
- [x] Check login process
- [x] Check emails are sending properly or not
- [x] Check DB is filling properly or not

If anything fails please create a backlog ticket to be worked upon with status as BLOCKED

**Comment by Xaptured** [comment]
Need to create a backlog ticket for add loader when sending email to client.

-  Add loader while sending email to client
